"""Interactive first-run setup: collects credentials, writes .env, and
generates a ready-to-use GitHub Actions workflow so the pipeline can run on
a schedule without relying on a local machine staying awake.
"""

from __future__ import annotations

from pathlib import Path

ENV_TEMPLATE = """\
# Generated by `python main.py --setup` on {timestamp}
TELEGRAM_BOT_TOKEN={telegram_bot_token}
TELEGRAM_CHAT_ID={telegram_chat_id}
LLM_PROVIDER={llm_provider}
GROQ_API_KEY={groq_api_key}
GEMINI_API_KEY={gemini_api_key}
PODCAST_CADENCE={cadence}
GROQ_MODEL={groq_model}
GEMINI_MODEL={gemini_model}
EDGE_TTS_VOICE={edge_tts_voice}
TARGET_BITRATE_KBPS={target_bitrate_kbps}
MAX_ARTICLES={max_articles}
GEMINI_REQUESTS_PER_MINUTE={gemini_requests_per_minute}
"""

WORKFLOW_TEMPLATE = """\
name: AI News Podcast ({cadence})

on:
  workflow_dispatch: {{}}
  schedule:
    # {cron_comment}
    - cron: "{cron_expr}"

jobs:
  generate-and-send:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install ffmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Generate and deliver podcast
        env:
          TELEGRAM_BOT_TOKEN: ${{{{ secrets.TELEGRAM_BOT_TOKEN }}}}
          TELEGRAM_CHAT_ID: ${{{{ secrets.TELEGRAM_CHAT_ID }}}}
          LLM_PROVIDER: {llm_provider}
          GROQ_API_KEY: ${{{{ secrets.GROQ_API_KEY }}}}
          GEMINI_API_KEY: ${{{{ secrets.GEMINI_API_KEY }}}}
          MAX_ARTICLES: "{max_articles}"
          PODCAST_CADENCE: {cadence}
        run: python main.py --run
"""

CRON_BY_CADENCE = {
    # 06:00 UTC = 08:00 CEST daily
    "daily": ("0 6 * * *", "Runs every day at 06:00 UTC (08:00 CEST)"),
    # 06:00 UTC = 08:00 CEST every Monday
    "weekly": ("0 6 * * 1", "Runs every Monday at 06:00 UTC (08:00 CEST)"),
}


def _prompt(label: str, default: str | None = None) -> str:
    suffix = f" [{default}]" if default else ""
    while True:
        value = input(f"{label}{suffix}: ").strip()
        if not value and default is not None:
            return default
        if value:
            return value
        print("  This value is required.")


def _prompt_optional(label: str) -> str:
    return input(f"{label} (optional, press enter to skip): ").strip()


def _prompt_choice(label: str, choices: list[str], default: str) -> str:
    choices_display = "/".join(c.upper() if c == default else c for c in choices)
    while True:
        value = input(f"{label} ({choices_display}) [{default}]: ").strip().lower()
        if not value:
            return default
        if value in choices:
            return value
        print(f"  Please enter one of: {', '.join(choices)}")


def run_setup(project_root: Path) -> None:
    from datetime import datetime, timezone

    print("=" * 60)
    print("AI News Podcast -- Setup Wizard")
    print("=" * 60)
    print(
        "This will collect your credentials, write a local .env file, and\n"
        "generate a GitHub Actions workflow so the podcast can run on a\n"
        "schedule in the cloud (no need to keep your own machine on).\n"
    )

    telegram_bot_token = _prompt("Telegram Bot Token (from @BotFather)")
    telegram_chat_id = _prompt("Telegram Chat ID (your user/group/channel ID)")
    llm_provider = _prompt_choice(
        "LLM provider (Groq is free and fast; Gemini is a fallback)", ["groq", "gemini"], default="groq"
    )
    if llm_provider == "groq":
        groq_api_key = _prompt("Groq API key (from https://console.groq.com/keys)")
        gemini_api_key = _prompt_optional("Gemini API key, as a fallback")
    else:
        gemini_api_key = _prompt("Gemini API key (from Google AI Studio)")
        groq_api_key = _prompt_optional("Groq API key, as a fallback")
    cadence = _prompt_choice("Podcast cadence", ["daily", "weekly"], default="daily")

    env_content = ENV_TEMPLATE.format(
        timestamp=datetime.now(timezone.utc).isoformat(),
        telegram_bot_token=telegram_bot_token,
        telegram_chat_id=telegram_chat_id,
        llm_provider=llm_provider,
        groq_api_key=groq_api_key,
        gemini_api_key=gemini_api_key,
        cadence=cadence,
        groq_model="openai/gpt-oss-120b",
        gemini_model="gemini-3.6-flash",
        edge_tts_voice="en-US-ChristopherNeural",
        target_bitrate_kbps=48,
        max_articles=6,
        gemini_requests_per_minute=5,
    )
    env_path = project_root / ".env"
    env_path.write_text(env_content, encoding="utf-8")
    print(f"\nWrote credentials to {env_path}")

    cron_expr, cron_comment = CRON_BY_CADENCE[cadence]
    workflow_content = WORKFLOW_TEMPLATE.format(
        cadence=cadence,
        cron_expr=cron_expr,
        cron_comment=cron_comment,
        llm_provider=llm_provider,
        max_articles=6,
    )
    workflow_dir = project_root / ".github" / "workflows"
    workflow_dir.mkdir(parents=True, exist_ok=True)
    workflow_path = workflow_dir / f"{cadence}_podcast.yml"
    workflow_path.write_text(workflow_content, encoding="utf-8")
    print(f"Wrote GitHub Actions workflow to {workflow_path}")

    print(
        "\nNext steps:\n"
        "  1. Test locally:            python main.py --run --dry-run\n"
        "  2. Push this repo to GitHub.\n"
        "  3. In the GitHub repo settings, add these as Actions secrets\n"
        "     (Settings -> Secrets and variables -> Actions -> New repository secret):\n"
        "       TELEGRAM_BOT_TOKEN\n"
        "       TELEGRAM_CHAT_ID\n"
        "       GROQ_API_KEY (or GEMINI_API_KEY, matching your chosen provider)\n"
        "  4. The workflow will then run automatically on its schedule, or you\n"
        "     can trigger it manually from the Actions tab ('Run workflow').\n"
        "\nNote: .env is gitignored by default -- your secrets stay local and are\n"
        "only supplied to the cloud run via GitHub Actions secrets.\n"
    )
